@startuml StageNode-Call-SequenceDiagram
<style>
  /* Global style applied to all elements */
  	element {
		BackGroundColor: #ffffff
  	}
</style>
actor alexa
boundary ": stage_node_main" as main
alexa -> main : main(argc:int,argv:char**)
activate main
	main -[#red]>o? : ros::init(argc, argv)

	create control "StageNode:node" as node
	main -> node : node(argc, argv)
	activate node
		node -> node : ""readParams()""
		activate node
			node ->o? : ros::NodeHandle:param_nh("\~")
			node -[#red]>o? : param_nh.param("stage/master", _is_master_stage, false)
			node <[#red]-o? : "<node member filled>"
			loop 10 times
				note right of node: "stage/type"\t\t|  _type_stage \t\t"topics/output"\t\t| _topic_frame_out\n"stage/output_dir"\t|  _path_output\t\t"config/id"\t\t| _id_camera\n"topics/input/frame"|  _topic_frame_in\t"config/profile"\t\t| _profile\n"topics/input/imu"\t|  _topic_imu_in\t"config/method"\t| _method\n"config/opt/working_directory"| _path_working_directory\n"config/opt/output_directory"\t| _path_output
				node ->o? : std::string("uninitialised")
				node <-o? : std::string
				node -[#red]>o? : param_nh.param("<config_par>", <field>, std::string("uninitialised"))
				node <[#red]-o? : "<node member filled>"
			end
		deactivate node
		node -> node : setPaths()
		activate node
			alt _path_working_directory == "uninitialised"
				node -[#red]>o? : ros::package::getPath("realm_ros")
    			node <[#red]-o? : return std::string
			end
			node ->o? : io::dirExists(_path_profile)
    		node <-o? : return bool
    		alt "_path_profile doesnt exist"
    			group Function parameters
					node ->o? : std::runtime_error(\t"Error: Profile folder '" \n\t\t\t\t+ _path_profile \n\t\t\t\t+ "' was not found!")
					node <-o? : return std::runtime_error
				end
				node ->o? : throw(std::runtime_error("Error: Profile folder '" \n\t\t\t\t\t+ _path_profile \n\t\t\t\t\t+ "' was not found!"))
    		end
			node ->o? : io::dirExists(_path_output)
    			node <-o? : return bool
			alt "_path_output doesn´t exist"
				node ->o? : io::createDir(_path_output)
			end
			alt "_is_master_stage true"
				node ->o? : io::getDateTime()
    			node <-o? : return std::string
    			node ->o? : io::dirExists(_path_output + "/" + _dir_date_time)
    			node <-o? : return bool
    			alt "_path_output/dir_date_time doesn´t exist"
    				node ->o? : io::createDir(_path_output + "/" + _dir_date_time);
    			end
			end
		deactivate node
		node -> node : readStageSettings()
		activate node
			group Function parameters
				node ->o? : _type_stage.c_str()
				node <-o? : return const char*
            	node ->o? : _file_settings_stage.c_str()
				node <-o? : return const char*
            end
            node -[#red]>o? : ros::ROS_INFO("Descriptive string",\n\t\t\t_type_stage.c_str(),\n\t\t\t_file_settings_stage.c_str())
            note right : MACRO
            group Function parameters
				node ->o? : _type_stage.c_str()
				node <-o? : return const char*
            	node ->o? : (*_settings_stage)["type"].toString()
				node <-o? : return const std::string
            	node ->o? : (*_settings_stage)["type"].toString().c_str()
				node <-o? : return const char*
            end
            node -[#red]>o? : ros::ROS_INFO("Descriptive string",\n\t\t\t_type_stage.c_str(),\n\t\t\t(*_settings_stage)["type"].toString().c_str())
            note right : MACRO
        deactivate node
        group Function parameters
			node -[#red]>o? : ros::TransportHints()
			node <[#red]-o? : return tbd
    	end
    	node -[#red]>o? : _nh.subscribe(\t_topic_frame_in,\n\t\t\t5,\n\t\t\t&StageNode::subFrame,\n\t\t\tthis,\n\t\t\tros::TransportHints())
    	alt "_is_master_stage true"
    		group Function parameters
    			node -[#red]>o? : _nh.advertise<std_msgs::String>(\t"/realm/"\n\t\t\t\t\t\t\t+ _id_camera \n\t\t\t\t\t\t\t+ "/general/output_dir",\n\t\t\t\t\t\t\t5)
    			node <[#red]-o? : return tbd
    		end
    		node -[#red]>o? : _publisher.insert({\t"general/output_dir",\n\t\t\t\t_nh.advertise<std_msgs::String>(\t"/realm/"\n\t\t\t\t\t\t\t\t\t\t\t+ _id_camera\n\t\t\t\t\t\t\t\t\t\t\t+ "/general/output_dir",\n\t\t\t\t\t\t\t\t\t\t\t5)})
    		group Function parameters
    			node -[#red]>o? : _nh.advertise<sensor_msgs::NavSatFix>("/realm/"\n\t\t\t\t\t\t\t\t + _id_camera \n\t\t\t\t\t\t\t\t + "/general/gnss_base",\n\t\t\t\t\t\t\t\t 5)
    			node <[#red]-o? : return tbd
    		end
    		node -[#red]>o? : _publisher.insert({\t"general/gnss_base",\n\t\t\t\t_nh.advertise<sensor_msgs::NavSatFix>("/realm/"\n\t\t\t\t\t\t\t\t\t\t\t\t + _id_camera\n\t\t\t\t\t\t\t\t\t\t\t\t + "/general/gnss_base",\n\t\t\t\t\t\t\t\t\t\t\t\t 5)})
    	else 
    		group Function parameters
    			node -[#red]>o? : ros::TransportHints()
    			node <[#red]-o? : return tbd
    		end
    		node -[#red]>o? : _nh.subscribe(\t"/realm/"+ _id_camera +"/general/output_dir", \n\t\t\t5, \n\t\t\t&StageNode::subOutputPath, \n\t\t\tthis, \n\t\t\tros::TransportHints())
    	end
    	
    	loop 4 times
    		node -[#red]>o? : _nh.advertiseService(_topic_prefix + "request_<action>", \n\t\t\t\t  &StageNode::srv<Action>, \n\t\t\t\t  this);
    		note left : finish\nstop\nresume\nreset
    		node <[#red]-o? : return ros::ServiceServer
    	end
    	node -[#red]>o? : _nh.advertiseService(_topic_prefix + "change_param", \n\t\t\t\t  &StageNode::srvChangeParam, \n\t\t\t\t  this);
    	node <[#red]-o? : return ros::ServiceServer
    	group Function parameters 
    		node ->o? : _type_stage.c_str()
		node <-o? : return const char*
    		node ->o? : _file_settings_camera.c_str()
		node <-o? : return const char*
    	end
    	node -[#red]>o? : ROS_INFO("STAGE_NODE [%s]: : Loading camera from path:\\n\ t%s",\n\t\t _type_stage.c_str(),\n\t\t _file_settings_camera.c_str())
    	note left : MACRO
    	group Function parameters 
    		node ->o? : _type_stage.c_str()
		node <-o? : return const char*
		node ->o? : (*_settings_camera)["type"].toString()
		node <-o? : return std::string
    		node ->o? : (*_settings_camera)["type"].toString().c_str()
		node <-o? : return const char*
    	end
    	node -[#red]>o? : ROS_INFO("STAGE_NODE [%s]: : Detected camera model: '%s'",\n\t\t _type_stage.c_str(),\n\t\t (*_settings_camera)["type"].toString().c_str())
    	note left : MACRO
    	alt _type_stage == "pose_estimation"
    		node -> node : createStagePoseEstimation()
    		activate node
    			group Function parameters
    				node ->o? : _type_stage.c_str()
    				node <-o? : return const char*
    				node ->o? : _file_settings_method.c_str()
    				node <-o? : return const char*
    			end
    			node -[#red]>o? : ROS_INFO("STAGE_NODE [%s]: : Loading vslam settings from path:\\n\\ t%s",\n\t\t _type_stage.c_str(),\n\t\t _file_settings_method.c_str());
    			note left : MACRO
    			node ->o? : VisualSlamSettingsFactory::load(\t_file_settings_method,\n\t\t\t\t\t\t\t_path_profile + "/" + _type_stage + "/method");
    			node <-o? : return VisualSlamSettings::Ptr
    			group Function parameters
    				node ->o? : _type_stage.c_str()
    				node <-o? : return const char*
    				node ->o? : (*settings_vslam)["type"].toString()
    				node <-o? : return std::string
    				node ->o? : (*settings_vslam)["type"].toString().c_str()
    				node <-o? : return const char*
    			end
    			node -[#red]>o? : ROS_INFO("STAGE_NODE [%s]: : Detected vslam type: '%s'",\n\t\t _type_stage.c_str(),\n\t\t (*settings_vslam)["type"].toString().c_str())
    			note left : MACRO
    			node ->o? : (*_settings_stage)["use_imu"].toInt()
    			node <-o? : return int
    			alt (*_settings_stage)["use_imu"] > 0
    				node ->o? : std::make_shared<ImuSettings>()
    				node <-o? : return *ImuSettings
    				node ->o? : settings_imu->loadFromFile(_file_settings_imu)
    			end
    			group Function parameters
    				node ->o? : (*_settings_camera)["fps"].toDouble()
    				node <-o? : return double
    			end
    			node ->o? : std::make_shared<stages::PoseEstimation>(\t_settings_stage, \n\t\t\t\t\t\t\t\t\tsettings_vslam, \n\t\t\t\t\t\t\t\t\t_settings_camera, \n\t\t\t\t\t\t\t\t\tsettings_imu, \n\t\t\t\t\t\t\t\t\t(*_settings_camera)["fps"].toDouble())
    			node <-o? : return StageBase::Ptr
				group Function parameters
    				node -[#red]>o? : _nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)
  					node <[#red]-o? : return tbd
    			end
    			node -[#red]>o? : _publisher.insert({\t"output/frame",\n\t\t\t\t_nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)});
    			loop 7 times
					note right of node: pose/visual/utm\t| geometry_msgs::PoseStamped\npose/visual/wgs\t| geometry_msgs::PoseStamped\npose/visual/traj\t| nav_msgs::Path\npose/gnss/utm\t\t| geometry_msgs::PoseStamped\npose/gnss/wgs\t\t| geometry_msgs::PoseStamped\npose/gnss/traj\t\t| nav_msgs::Path\npointcloud\t\t| sensor_msgs::PointCloud2
					group Function parameters
						skinparam guillemet false
						node -[#red]>o? : _nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)
						node <[#red]-o? : return tbd
					end
					node -[#red]>o? : _publisher.insert({\t"output/<parameter>",\n\t\t\t\t_nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)});
				end
				group Function parameters
    				node -[#red]>o? : _nh.advertise<sensor_msgs::Image>(_topic_prefix + "tracked", 5)
  					node <[#red]-o? : return tbd
    			end
    			node -[#red]>o? : _publisher.insert({\t"debug/tracked",\n\t\t\t\t_nh.advertise<sensor_msgs::Image>(_topic_prefix + "tracked", 5)})
				alt _topic_imu_in != "uninitialised"
					group Function paramaters
						node -[#red]>o? : ros::TransportHints()
						node <[#red]-o? : return tbd
					end
					node -[#red]>o? : _nh.subscribe(_topic_imu_in, 100, &StageNode::subImu, this, ros::TransportHints())
				end
    		deactivate node
    	end
    	alt _type_stage == "densification"
    		node -> node : createStageDensification()
    		activate node
    			group Function paramaters
    				node ->o? : _type_stage.c_str()
    				node <-o? : return const char*
    				node ->o? : _file_settings_method.c_str()
    				node <-o? : return const char*
    			end
  				node -[#red]>o? : ROS_INFO("STAGE_NODE [%s]: : Loading densifier settings from path:\\n\ t%s",\n\t\t _type_stage.c_str(), \n\t\t _file_settings_method.c_str())
    			note left : MACRO
    			node ->o? : DensifierSettingsFactory::load(_file_settings_method, \n\t\t\t\t\t\t _path_profile + "/" + _type_stage + "/method")
    			node <-o? : return DensifierSettings::Ptr
    			group Function paramaters
    				node ->o? : _type_stage.c_str()
    				node <-o? : return const char*
    				node ->o? : (*settings_densifier)["type"].toString()
    				node <-o? : return std::string
    				node ->o? : (*settings_densifier)["type"].toString().c_str()
    				node <-o? : return const char*
    			end
    			node -[#red]>o? : ROS_INFO(\t"STAGE_NODE [%s]: : Detected densifier type: '%s'",\n\t\t\t_type_stage.c_str(),\n\t\t\t(*settings_densifier)["type"].toString().c_str())
    			note left : MACRO
				group Function paramaters
					node ->o? : (*_settings_camera)["fps"].toDouble()
					node <-o? : return double
				end
				node ->o? : std::make_shared<stages::Densification>(\t_settings_stage,\n\t\t\t\t\t\t\t\t\tsettings_densifier,\n\t\t\t\t\t\t\t\t\t(*_settings_camera)["fps"].toDouble())
				node <-o? : return StageBase::Ptr
				group Function parameters
    				node -[#red]>o? : _nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)
  					node <[#red]-o? : return tbd
    			end
    			node -[#red]>o? : _publisher.insert({\t"output/frame",\n\t\t\t\t_nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)})
    			loop 5 times
					note right of node: pose/utm\t\t| geometry_msgs::PoseStamped\npose/wgs\t\t| geometry_msgs::PoseStamped\npointcloud\t| sensor_msgs::PointCloud2\ndepth\t\t| sensor_msgs::Image\ndepth_display\t| sensor_msgs::Image
					group Function parameters
						skinparam guillemet false
						node -[#red]>o? : _nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)
						node <[#red]-o? : return tbd
					end
					node -[#red]>o? : _publisher.insert({\t"output/<parameter>",\n\t\t\t\t_nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)})
				end
				group Function parameters
					skinparam guillemet false
					node -[#red]>o? : _nh.advertise<sensor_msgs::Image>(_topic_prefix + "img", 5)
					node <[#red]-o? : return tbd
				end
    			node -[#red]>o? : _publisher.insert({\t"output/img_rectified",\n\t\t\t\t_nh.advertise<sensor_msgs::Image>(_topic_prefix + "img", 5)})
			deactivate node
    	end
		alt _type_stage == "surface_generation"
			node -> node : createStageSurfaceGeneration()
			activate node
				group Function paramaters
					node ->o? : (*_settings_camera)["fps"].toDouble()
					node <-o? : return double
				end
				node ->o? : std::make_shared<stages::SurfaceGeneration>(\t_settings_stage,\n\t\t\t\t\t\t\t\t\t\t(*_settings_camera)["fps"].toDouble())
				node <-o? : return StageBase::Ptr
				group Function parameters
						node -[#red]>o? : _nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)
						node <[#red]-o? : return tbd
				end
				node -[#red]>o? : _publisher.insert({\t"output/frame",\n\t\t\t\t_nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)})
				group Function parameters
					skinparam guillemet false
					node -[#red]>o? : _nh.advertise<sensor_msgs::Image>(_topic_prefix + "elevation_map", 5)
					node <[#red]-o? : return tbd
				end
    			node -[#red]>o? : _publisher.insert({\t"output/elevation_map",\n\t\t\t\t_nh.advertise<sensor_msgs::Image>(_topic_prefix + "elevation_map", 5)})
			deactivate node
		end
		alt _type_stage == "ortho_rectification"
			node -> node : createStageOrthoRectification()
			activate node
				group Function paramaters
					node ->o? : (*_settings_camera)["fps"].toDouble()
					node <-o? : return double
				end
				node ->o? : std::make_shared<stages::OrthoRectification>(\t_settings_stage,\n\t\t\t\t\t\t\t\t\t\t(*_settings_camera)["fps"].toDouble())
				node <-o? : return StageBase::Ptr
				group Function parameters
						node -[#red]>o? : _nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)
						node <[#red]-o? : return tbd
				end
				node -[#red]>o? : _publisher.insert({\t"output/frame",\n\t\t\t\t_nh.advertise<realm_msgs::Frame>(_topic_frame_out, 5)})
				loop 2 times
					note right of node: rectified\t\t| sensor_msgs::Image\npointcloud\t| sensor_msgs::PointCloud2
					group Function parameters
						skinparam guillemet false
						node -[#red]>o? : _nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)
						node <[#red]-o? : return tbd
					end
					node -[#red]>o? : _publisher.insert({\t"output/<parameter>",\n\t\t\t\t_nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)})
				end
			deactivate node
		end
		alt _type_stage == "mosaicing"
			node -> node : createStageMosaicing()
			activate node
				group Function paramaters
					node ->o? : (*_settings_camera)["fps"].toDouble()
					node <-o? : return double
				end
				node ->o? : std::make_shared<stages::Mosaicing>(_settings_stage,\n\t\t\t\t\t\t\t\t(*_settings_camera)["fps"].toDouble())
				node <-o? : return StageBase::Ptr
				loop 5 times
					note right of node: rgb\t\t\t| sensor_msgs::Image\nelevation\t\t| sensor_msgs::Image\npointcloud\t| sensor_msgs::PointCloud2\nmesh\t\t| visualization_msgs::Marker\nupdate/ortho\t| realm_msgs::GroundImageCompressed
					group Function parameters
						skinparam guillemet false
						node -[#red]>o? : _nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)
						node <[#red]-o? : return tbd
					end
					node -[#red]>o? : _publisher.insert({\t"output/<parameter>",\n\t\t\t\t_nh.advertise<<type>>(_topic_prefix + "<parameter>", 5)})
				end
			deactivate node
		end
		alt _type_stage == "tileing"
			node -> node : createStageTileing()
			activate node
				group Function paramaters
					node ->o? : (*_settings_camera)["fps"].toDouble()
					node <-o? : return double
				end
				node ->o? : std::make_shared<stages::Tileing>(\t_settings_stage,\n\t\t\t\t\t\t\t\t(*_settings_camera)["fps"].toDouble())
				node <-o? : return StageBase::Ptr
			deactivate node
		end

		node -> node : linkStageTransport()
		activate node
			loop 5 times
				note right of node: StageNode::pubFrame\nStageNode::pubPointCloud\nStageNode::pubImage\nStageNode::pubDepthMap\nStageNode::pubMesh
				node ->o? : std::bind(&<type>, this, ph::_1, ph::_2);
				node <-o? : return tbd
			end
			node ->o? : std::bind(&StageNode::pubPose, this, ph::_1, ph::_2, ph::_3, ph::_4);
			node <-o? : return tbd
			node ->o? : std::bind(&StageNode::pubCvGridMap, this, ph::_1, ph::_2, ph::_3, ph::_4);
			node <-o? : return tbd
			node ->o? : _stage->registerFrameTransport(transport_frame);
			node ->o? : _stage->registerPoseTransport(transport_pose);
			node ->o? : _stage->registerPointCloudTransport(transport_pointcloud);
			node ->o? : _stage->registerImageTransport(transport_img);
			node ->o? : _stage->registerDepthMapTransport(transport_img);
			node ->o? : _stage->registerMeshTransport(transport_mesh);
			node ->o? : _stage->registerCvGridMapTransport(transport_cvgridmap);
		deactivate node
		alt "_is_master_stage true"
		node ->o? : _stage->initStagePath(_path_output + "/" + _dir_date_time)
		end
		node ->o? : _stage->start()
		group Function parameters
			node ->o? : _type_stage.c_str()
		end
		node -[#red]>o? : ROS_INFO(\t"STAGE_NODE [%s]: Started stage node successfully!", \n\t\t\t_type_stage.c_str())
		return
	deactivate node
	' what does this do, ask harley.
	main -[#red]>o? : rate(100)
	main <[#red]-o? : return ros::Rate
	loop node.isOkay()
		group Loop criteria
			main -> node : node.isOkay()
			activate node
				node ->o? : lock(_mutex_do_shutdown)
				node <-o? : return  std::unique_lock<std::mutex>
				group Return parameters
					node -[#red]>o? : _nh.ok()
				end
				return boolean
			deactivate node
		end
		main -[#red]>o? : ros::spinOnce()
		main -> node : node.spin()
		activate node
			alt "_is_master_stage true"
				' Ask Harley where _publisher belongs, is it ros or realm
				node ->o? : _publisher["general/output_dir"].publish(msg)
			end
			alt "_is_tf_base_initialized & _is_master_stage both true"
				group Function parameters
					group Function parameters
						node -[#red]>o? : ros::Time::now()
						node <[#red]-o? : return tbd 
					end
					' Ask if this is a constructor
					node ->o? : tf::StampedTransform(\t_tf_base,\n\t\t\t\t\tros::Time::now(),\n\t\t\t\t\t"utm",\n\t\t\t\t\t_tf_base_frame_name)
					node <-o? : return tbd
				end
				' Ask Harley where tf is, ros or realm
				node ->o? :  br.sendTransform(tf::StampedTransform(_tf_base,\n\t\t\t\t\t\t\t\t  ros::Time::now(),\n\t\t\t\t\t\t\t\t  "utm",\n\t\t\t\t\t\t\t\t  _tf_base_frame_name))
				' Ask about _publisher
				node ->o? : _publisher["general/gnss_base"].publish(_gnss_base)
			end
			alt "_is_tf_stage_initialized true"
				group Function parameters
					group Function parameters
						node -[#red]>o? : ros::Time::now()
						node <[#red]-o? : retrun tbd
					end
					' Ask harley about tf and if this is a constructor
					node ->o? : tf::StampedTransform(\t_tf_stage,\n\t\t\t\t\tros::Time::now(),\n\t\t\t\t\t_tf_base_frame_name,\n\t\t\t\t\t_tf_stage_frame_name)
					node <-o? : return tbd
				end
				' check if br is ros or not
				node ->o? : br.sendTransform(tf::StampedTransform(_tf_stage,\n\t\t\t\t\t\t\t\t  ros::Time::now(),\n\t\t\t\t\t\t\t\t  _tf_base_frame_name,\n\t\t\t\t\t\t\t\t  _tf_stage_frame_name))
			end
			return
		deactivate node
		main -[#red]>o? : rate.sleep()
	end
	main -[#red]>o? : ros::shutdown()
	main --> alexa : return 0
deactivate main
@enduml
